#define __PINSET__ 1

#if __PINSET__
// BUTTON_1 and BUTTON_2 use only
#define DEF_BUTTON_1 NRF_GPIO_PIN_MAP(0, 11) //13  //11
#define DEF_BUTTON_2 NRF_GPIO_PIN_MAP(0, 24) //24
//#define DEF_BUTTON_3 NRF_GPIO_PIN_MAP(0, 31)
//#define DEF_BUTTON_4 NRF_GPIO_PIN_MAP(0, 29)
#define DEF_BUTTON_RESET NRF_GPIO_PIN_MAP(0, 18)
#define SDA_PIN NRF_GPIO_PIN_MAP(0, 2)
#define SCL_PIN NRF_GPIO_PIN_MAP(0, 30)
#define ACCEL_INT_PIN NRF_GPIO_PIN_MAP(0, 12)
#define GPIO_BM1383_OUTPUT_PIN NRF_GPIO_PIN_MAP(0, 4) // used to control supply voltage on BM1383AGLV

#else
#define DEF_BUTTON_1 NRF_GPIO_PIN_MAP(0, 2)
#define DEF_BUTTON_2 NRF_GPIO_PIN_MAP(0, 29)
#define DEF_BUTTON_3 NRF_GPIO_PIN_MAP(0, 31)
#define DEF_BUTTON_4 NRF_GPIO_PIN_MAP(0, 30)
#define DEF_BUTTON_RESET NRF_GPIO_PIN_MAP(0, 18)
#define SDA_PIN NRF_GPIO_PIN_MAP(0, 13)
#define SCL_PIN NRF_GPIO_PIN_MAP(0, 24)
#define ACCEL_INT_PIN NRF_GPIO_PIN_MAP(0, 12)
#define GPIO_BM1383_OUTPUT_PIN NRF_GPIO_PIN_MAP(0, 4)

// external version
//#define DEF_BUTTON_1 NRF_GPIO_PIN_MAP(0, 2)
//#define DEF_BUTTON_2 NRF_GPIO_PIN_MAP(0, 29)
//#define DEF_BUTTON_3 NRF_GPIO_PIN_MAP(0, 31)
//#define DEF_BUTTON_4 NRF_GPIO_PIN_MAP(0, 30)
//#define DEF_BUTTON_RESET NRF_GPIO_PIN_MAP(0, 18)
//#define SDA_PIN NRF_GPIO_PIN_MAP(0, 22)
//#define SCL_PIN NRF_GPIO_PIN_MAP(1, 0)
//#define ACCEL_INT_PIN NRF_GPIO_PIN_MAP(0, 12)
#endif